version: '3.8'

services:
  db:
    image: postgres
    container_name: banking_system_db
    restart: always
    environment:
      POSTGRES_DB: BANKING_SYSTEM
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: banking_system-postgres-db